#!/bin/bash
# =============================================================================
# analyze.sh — リポジトリを分析して改善 Issue を自動作成する
# Usage: ./analyze.sh --repo OWNER/REPO [--max-issues 3] [--max-turns 15]
# =============================================================================
set -euo pipefail

# --- ネストセッション回避 ---
unset CLAUDECODE 2>/dev/null || true

# --- デフォルト値 ---
MAX_ISSUES=3
MAX_TURNS=15
MODEL="claude-sonnet-4-6"
REPO=""
AUTO_YES=false
WORK_BASE="/tmp/claude-runner"

# --- 引数パース ---
while [[ $# -gt 0 ]]; do
  case $1 in
    --repo)       REPO="$2";       shift 2 ;;
    --max-issues) MAX_ISSUES="$2"; shift 2 ;;
    --max-turns)  MAX_TURNS="$2";  shift 2 ;;
    --model)      MODEL="$2";      shift 2 ;;
    --yes|-y)     AUTO_YES=true;   shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ -z "$REPO" ]]; then
  echo "Usage: $0 --repo OWNER/REPO [--max-issues N] [--max-turns N] [--model MODEL] [--yes]"
  exit 1
fi

REPO_NAME="${REPO##*/}"
WORK_DIR="${WORK_BASE}/${REPO_NAME}"
LOG_DIR="${HOME}/.claude-runner/logs"
LOG_FILE="${LOG_DIR}/${REPO_NAME}-analyze-$(date +%Y%m%d-%H%M%S).log"

mkdir -p "$LOG_DIR"

# --- ログ関数 ---
log() { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

# --- リポジトリ準備 ---
log "=== ${REPO} の分析を開始 ==="

if [[ -d "$WORK_DIR/.git" ]]; then
  log "既存のローカルリポジトリを更新"
  cd "$WORK_DIR"
  git checkout main 2>/dev/null || git checkout master
  git pull --ff-only
else
  log "リポジトリをクローン"
  mkdir -p "$WORK_BASE"
  gh repo clone "$REPO" "$WORK_DIR"
  cd "$WORK_DIR"
fi

# --- 既存 Issue のタイトル一覧を取得 ---
log "既存の Issue を確認中..."
EXISTING_ISSUES=$(gh issue list --repo "$REPO" --state all --limit 500 --json title --jq '.[].title' 2>/dev/null || true)

# --- Claude Code で分析 ---
PROMPT="あなたはこのリポジトリのコードレビュアーです。コードベースを読んで改善点を洗い出し、GitHub Issue として提案してください。

## ルール
- 最大 ${MAX_ISSUES} 件の Issue を提案する
- 各 Issue は **1つの小さな変更** に絞る（関数1個追加、バグ1件修正、リファクタ1箇所など）
- 1つの Issue で複数ファイルにまたがる大きな変更は避ける
- 実際にコードを読んで具体的な問題を指摘する（一般論は不要）
- body には「何が問題で、どう直すべきか」を簡潔に書く

## 既存の Issue（重複しないこと）
${EXISTING_ISSUES:-なし}

## 出力形式
以下の JSON 配列のみを出力してください。前後に説明文やマークダウンのコードフェンスは付けないでください。
[
  {
    \"title\": \"Issue タイトル\",
    \"body\": \"Issue の本文（Markdown可）\"
  }
]"

log "Claude Code を起動 (max-turns: ${MAX_TURNS}, model: ${MODEL})"

RESULT_FILE=$(mktemp)
CLAUDE_EXIT=0
claude -p "$PROMPT" \
  --max-turns "$MAX_TURNS" \
  --model "$MODEL" \
  --dangerously-skip-permissions \
  --output-format json \
  < /dev/null \
  2>>"$LOG_FILE" > "$RESULT_FILE" || CLAUDE_EXIT=$?

if [[ "$CLAUDE_EXIT" -ne 0 ]]; then
  log "Claude Code がエラーで終了 (exit code: ${CLAUDE_EXIT})"
  rm -f "$RESULT_FILE"
  exit 1
fi

# --- JSON をパース ---
# --output-format json の場合、result フィールドにテキストが入る
RAW_RESULT=$(jq -r '.result // empty' "$RESULT_FILE" 2>/dev/null || cat "$RESULT_FILE")
rm -f "$RESULT_FILE"

# コードフェンスで囲まれている場合は除去
CLEAN_JSON=$(echo "$RAW_RESULT" | sed -n '/^\[/,/^\]/p')
if [[ -z "$CLEAN_JSON" ]]; then
  # sed で取れなかった場合はそのまま使う
  CLEAN_JSON="$RAW_RESULT"
fi

# JSON として有効か確認
if ! echo "$CLEAN_JSON" | jq empty 2>/dev/null; then
  log "Claude の出力が有効な JSON ではありません"
  log "出力内容:"
  echo "$RAW_RESULT" | tee -a "$LOG_FILE"
  exit 1
fi

ISSUE_COUNT=$(echo "$CLEAN_JSON" | jq 'length')

if [[ "$ISSUE_COUNT" -eq 0 ]]; then
  log "提案された Issue はありません"
  exit 0
fi

# --- 一覧表示 ---
echo ""
echo "📋 提案された Issue (${ISSUE_COUNT}件):"
echo ""

for i in $(seq 0 $((ISSUE_COUNT - 1))); do
  TITLE=$(echo "$CLEAN_JSON" | jq -r ".[$i].title")
  # body の先頭行を要約として表示
  SUMMARY=$(echo "$CLEAN_JSON" | jq -r ".[$i].body" | head -1)
  echo "  $((i + 1)). ${TITLE}"
  echo "     → ${SUMMARY}"
  echo ""
done

# --- ユーザー確認 ---
if [[ "$AUTO_YES" == "true" ]]; then
  SELECTION="y"
  echo "作成する Issue を選択 [y=全件 / n=中止 / 番号(カンマ区切り)]: y (--yes)"
else
  echo -n "作成する Issue を選択 [y=全件 / n=中止 / 番号(カンマ区切り)]: "
  if [[ -t 0 ]]; then
    read -r SELECTION
  elif [[ -e /dev/tty ]]; then
    read -r SELECTION < /dev/tty
  else
    log "対話入力が利用できません。--yes オプションで全件作成するか、ターミナルから実行してください。"
    exit 1
  fi
fi

if [[ "$SELECTION" == "n" || "$SELECTION" == "N" ]]; then
  log "中止しました"
  exit 0
fi

# 選択された番号を配列に変換
if [[ "$SELECTION" == "y" || "$SELECTION" == "Y" ]]; then
  SELECTED=($(seq 1 "$ISSUE_COUNT"))
else
  IFS=',' read -ra SELECTED <<< "$SELECTION"
fi

# --- claude-task ラベルを確保 ---
gh label create "claude-task" --repo "$REPO" --force 2>/dev/null || true

# --- Issue 作成 ---
CREATED=0
for NUM in "${SELECTED[@]}"; do
  NUM=$(echo "$NUM" | tr -d ' ')
  INDEX=$((NUM - 1))

  if [[ "$INDEX" -lt 0 || "$INDEX" -ge "$ISSUE_COUNT" ]]; then
    log "無効な番号: ${NUM} (スキップ)"
    continue
  fi

  TITLE=$(echo "$CLEAN_JSON" | jq -r ".[$INDEX].title")
  BODY=$(echo "$CLEAN_JSON" | jq -r ".[$INDEX].body")

  ISSUE_URL=$(gh issue create \
    --repo "$REPO" \
    --title "$TITLE" \
    --body "${BODY}

---
🤖 Generated by [claude-runner](https://github.com/taku-me/claude-runner) analyze" \
    --label "claude-task")

  log "Issue 作成: ${ISSUE_URL}"
  CREATED=$((CREATED + 1))
done

log "=== 完了: ${CREATED} 件の Issue を作成 ==="
