#!/bin/bash
# =============================================================================
# run-task.sh — GitHub Issue を読んで Claude Code で解決し PR を出す
# Usage: ./run-task.sh --repo OWNER/REPO --issue NUMBER [--max-turns 30]
# =============================================================================
set -euo pipefail

# --- エラー時にラベルを claude-failed に戻す ---
on_error() {
  local exit_code=$?
  if [[ -n "${REPO:-}" && -n "${ISSUE:-}" ]]; then
    echo "[$(date '+%H:%M:%S')] エラー発生 (exit code: ${exit_code}) — ラベルを claude-failed に変更" | tee -a "${LOG_FILE:-/dev/null}"
    gh issue edit "$ISSUE" --repo "$REPO" --remove-label "claude-working" --add-label "claude-failed" 2>/dev/null || true
  fi
  exit "$exit_code"
}
trap on_error ERR

# --- ネストセッション回避 ---
unset CLAUDECODE 2>/dev/null || true

# --- デフォルト値 ---
MAX_TURNS=30
REPO=""
ISSUE=""
AUTO_MERGE=false
WORK_BASE="/tmp/claude-runner"

# --- 引数パース ---
while [[ $# -gt 0 ]]; do
  case $1 in
    --repo)        REPO="$2";       shift 2 ;;
    --issue)       ISSUE="$2";      shift 2 ;;
    --max-turns)   MAX_TURNS="$2";  shift 2 ;;
    --auto-merge)  AUTO_MERGE=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ -z "$REPO" || -z "$ISSUE" ]]; then
  echo "Usage: $0 --repo OWNER/REPO --issue NUMBER [--max-turns N] [--auto-merge]"
  exit 1
fi

REPO_NAME="${REPO##*/}"
WORK_DIR="${WORK_BASE}/${REPO_NAME}"
BRANCH="claude/issue-${ISSUE}"
LOG_DIR="${HOME}/.claude-runner/logs"
LOG_FILE="${LOG_DIR}/${REPO_NAME}-issue-${ISSUE}-$(date +%Y%m%d-%H%M%S).log"

mkdir -p "$LOG_DIR"

# --- ログ関数 ---
log() { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

# --- ラベル操作 ---
set_label() {
  local from="$1" to="$2"
  gh issue edit "$ISSUE" --repo "$REPO" --remove-label "$from" --add-label "$to" 2>/dev/null || true
}

# --- Issue 読み込み ---
log "=== Issue #${ISSUE} の処理を開始 (${REPO}) ==="

ISSUE_JSON=$(gh issue view "$ISSUE" --repo "$REPO" --json title,body,labels)
ISSUE_TITLE=$(echo "$ISSUE_JSON" | jq -r '.title')
ISSUE_BODY=$(echo "$ISSUE_JSON" | jq -r '.body // "No description provided."')

log "Title: ${ISSUE_TITLE}"

# ラベルを working に変更
set_label "claude-task" "claude-working"

# --- リポジトリ準備 ---
if [[ -d "$WORK_DIR/.git" ]]; then
  log "既存のローカルリポジトリを更新"
  cd "$WORK_DIR"
  git checkout main 2>/dev/null || git checkout master
  git clean -fd
  git checkout -- .
  git pull --ff-only
else
  log "リポジトリをクローン"
  mkdir -p "$WORK_BASE"
  gh repo clone "$REPO" "$WORK_DIR"
  cd "$WORK_DIR"
fi

DEFAULT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# 既存ブランチがあれば削除してクリーンな状態にする
git branch -D "$BRANCH" 2>/dev/null || true
git checkout -b "$BRANCH"

log "ブランチ: ${BRANCH}"

# --- Claude Code 実行 ---
PROMPT="あなたはこのリポジトリの開発者です。以下の GitHub Issue を解決してください。

## Issue #${ISSUE}: ${ISSUE_TITLE}

${ISSUE_BODY}

## 作業手順
1. まず CLAUDE.md があれば読んで、プロジェクトの規約を把握する
2. コードベースを調査して、Issue の内容を理解する
3. 必要な変更を実装する
4. テストがあれば実行して、既存テストが通ることを確認する
5. 変更内容を git commit する（コミットメッセージは日本語でも英語でもよい）

## 注意事項
- 既存のコードスタイル・アーキテクチャに従うこと
- 最小限の変更で Issue を解決すること
- 不明点があっても人間に聞けないので、最善の判断で進めること
- PR の作成は不要（このスクリプトが行う）"

log "Claude Code を起動 (max-turns: ${MAX_TURNS})"

CLAUDE_EXIT=0
claude -p "$PROMPT" \
  --max-turns "$MAX_TURNS" \
  --dangerously-skip-permissions \
  --verbose < /dev/null 2>&1 | tee -a "$LOG_FILE" || CLAUDE_EXIT=$?

# --- 結果判定 ---
# Claude Code がコミット済みの場合: DEFAULT_BRANCH..HEAD に差分がある
# Claude Code が未コミットの場合: git status --porcelain に差分がある
UNCOMMITTED=$(git status --porcelain)
COMMITTED=$(git log "${DEFAULT_BRANCH}..HEAD" --oneline 2>/dev/null || true)

if [[ -z "$UNCOMMITTED" && -z "$COMMITTED" ]]; then
  log "変更なし — Claude は修正を行いませんでした"
  set_label "claude-working" "claude-failed"
  gh issue comment "$ISSUE" --repo "$REPO" --body "$(cat <<EOF
🤖 **Claude Runner**: 自動処理を試みましたが、コード変更は生成されませんでした。

- Max turns: ${MAX_TURNS}
- Exit code: ${CLAUDE_EXIT}
- ログ: \`${LOG_FILE}\`

手動での対応が必要かもしれません。
EOF
)"
  exit 1
fi

# --- コミット漏れの変更があればステージング ---
if [[ -n "$UNCOMMITTED" ]]; then
  git add -A
  git commit -m "Claude auto-fix for issue #${ISSUE}: ${ISSUE_TITLE}"
fi

# --- CLAUDE_EXIT 非ゼロ時の警告文を生成 ---
CLAUDE_WARNING=""
if [[ "$CLAUDE_EXIT" -ne 0 ]]; then
  CLAUDE_WARNING=$'\n> ⚠️ Claude Code は終了コード '"${CLAUDE_EXIT}"' で終了しました。実装が不完全な可能性があります。\n'
fi

# --- Push & PR 作成 ---
git push -u origin "$BRANCH" --force-with-lease

# 既存 PR があるか確認
EXISTING_PR=$(gh pr list --repo "$REPO" --head "$BRANCH" --json url --jq '.[0].url // empty' 2>/dev/null || true)

if [[ -n "$EXISTING_PR" ]]; then
  PR_URL="$EXISTING_PR"
  log "既存 PR を更新: ${PR_URL}"
else
  PR_URL=$(gh pr create \
    --repo "$REPO" \
    --base "$DEFAULT_BRANCH" \
    --head "$BRANCH" \
    --title "🤖 #${ISSUE}: ${ISSUE_TITLE}" \
    --body "$(cat <<EOF
## Summary
Closes #${ISSUE}

この PR は Claude Code によって自動生成されました。
${CLAUDE_WARNING}
## Issue
${ISSUE_TITLE}

## 変更内容
$(git log "${DEFAULT_BRANCH}..HEAD" --oneline)

---
⚠️ **人間によるレビューが必要です。** マージ前にコードを確認してください。

🤖 Generated by [claude-runner](https://github.com/taku-me/claude-runner)
EOF
)")
  log "PR 作成完了: ${PR_URL}"
fi

# --- Auto-merge ---
if [[ "$AUTO_MERGE" == "true" ]]; then
  log "Auto-merge: PR をマージ中..."
  if gh pr merge "$PR_URL" --repo "$REPO" --merge --delete-branch 2>&1 | tee -a "$LOG_FILE"; then
    log "Auto-merge: 成功"
    set_label "claude-working" "claude-done"
    gh issue comment "$ISSUE" --repo "$REPO" --body "$(cat <<EOF
🤖 **Claude Runner**: PR を作成し、自動マージしました → ${PR_URL}
EOF
)"
  else
    log "Auto-merge: 失敗（コンフリクトの可能性）— 手動レビューが必要です"
    set_label "claude-working" "claude-done"
    gh issue comment "$ISSUE" --repo "$REPO" --body "$(cat <<EOF
🤖 **Claude Runner**: PR を作成しましたが、自動マージに失敗しました → ${PR_URL}

手動でのレビュー・マージをお願いします。
EOF
)"
  fi
else
  # ラベルを done に変更
  set_label "claude-working" "claude-done"
  gh issue comment "$ISSUE" --repo "$REPO" --body "$(cat <<EOF
🤖 **Claude Runner**: PR を作成しました → ${PR_URL}

レビューをお願いします。
EOF
)"
fi

log "=== Issue #${ISSUE} の処理完了 ==="
